### ISSUE TITLE
NVAPI_ACCESS_DENIED

### ISSUE THREAD

**Issue by JarBinks** [DeadManWalkingTO/NVidiaProfileInspectorDmW#9]
I am getting the message below when trying to update some settings.
  DRS_SaveSettings failed: NVAPI_ACCESS_DENIED

Specifically when trying to modify "CUDA - Force P2 State" = "Off".
I am on Win10.
I have searched a few times and tried a few things:
  - DDU and reinstall NVidia drivers
  - Safe Mode, DDU and reinstall NVidia drivers
  - Looked for read only files
  - Logged in to local admin account

I am sure it is something about my setup but I have not been able to find it.
Any hit you can give would be appreciated.

I am comfortable examining, writing or modifying code if need be.

Thanks!!
![image](https://user-images.githubusercontent.com/18104455/43679484-d84820f8-97f3-11e8-88f2-3819d58d196b.png)

**Comment by DeadManWalkingTO** [comment]
I try to find the problem. (Please give me few days. Thank you!)

**Comment by DeadManWalkingTO** [comment]
**NVAPI_ACCESS_DENIED**
The issue is that when you installed your NVIDIA driver it didn't installed correctly!

**Solution:**
1. Look for the folder named Drs located in "C:\ProgramData\NVIDIA Corporation".
2. Delete the folder "Drs" (if its not there goto next step). 
3. Create a new folder with name "Drs".

Thats all.

**Comment by JarBinks** [comment]
I am sorry to say that it did not fix the issue.

I added the directory "C:\Program Files\NVIDIA Corporation\Drs", which did not exist.

Things I did after, but they did not work:
- I checked over the security on the new directory
- I updated to the latest version of Profile Inspector
- Rebooted the machine
- Checked the directory security

![image](https://user-images.githubusercontent.com/18104455/47511334-f9cc6600-d847-11e8-834e-456ecfaa195d.png)

**Comment by DeadManWalkingTO** [comment]
1. Remove all nVidia software and drivers. (Use [Display Driver Uninstaller - DDU](https://www.guru3d.com/files-details/display-driver-uninstaller-download.html)).
2. Reinstalling the latest Driver and PhysX ONLY (no 3D drivers, no GFEX).
3. Download the separate GeForce Experience package and install that afterwards. 
4. Feedback here!

Thank you!

**Comment by Squall-Leonhart** [comment]
It didn't work because you read the instructions wrong,

Deadman said "C:\ProgramData\NVIDIA Corporation"

You went to "Program Files"

**Comment by ohcibi** [comment]
@Squall-Leonhart is right. I wouldn't call this issue 'closed' though since the program could just create the folder itself it its missing and not fail with a meaningless error.

A caveat of the workaround is: the Folder `ProgramData` is hidden. One way to get there is to simply copy the path `C:\ProgramData\` into the address bar of the explorer window and hit enter. You don't need to enable hidden files with that approach.

**Comment by ohcibi** [comment]
@Deadmanwalking why has the issue been closed?? The bug is still present with the very latest version as I have said. The fact that one can workaround this does not mean that the problem itself got solved. For the matter of this issue the program should silently create the missing directory and not just fail with a meaningless error. Please re-open it.

**Comment by Squall-Leonhart** [comment]
no, it shouldn't create the folder, nor should it create the drs file if it is not present.
The folder should already exist and have files in it.
if it doesn't, run a Reset to Defaults in the NVCP.

**Comment by ohcibi** [comment]
@Squall-Leonhart then the error message should be updated to tell the exact problem.

**Comment by DeadManWalkingTO** [comment]
The "C: \ ProgramData \ NVIDIA Corporation" folder should already exist after installing the driver.
Something in your system is messing with your drivers.

1. Remove all nVidia software and drivers. (Use [Display Driver Uninstaller - DDU](https://www.guru3d.com/files-details/display-driver-uninstaller-download.html)).
2. Reinstalling the latest Driver and PhysX ONLY (no 3D drivers, no GFEX).
3. Check issue.
4. Download and install the separate GeForce Experience package.

I insist that the solution to this issue is
> **NVAPI_ACCESS_DENIED**
> The issue is that when you installed your NVIDIA driver it didn't installed correctly!
> **Solution:**
> 1. Look for the folder named Drs located in "C:\ProgramData\NVIDIA Corporation".
> 2. Delete the folder "Drs" (if its not there goto next step). 
> 3. Create a new folder with name "Drs".

Thank you!
